import Footer from "@/components/shared/Footer";
import Nabar from "@/components/shared/Nabar";
import VerseBackground from "@/components/shared/VerseBackground";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "츄니링크",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko_KR">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white dark:bg-background flex flex-col min-h-screen`}
      >
        <Nabar />
          <VerseBackground>
            <div className="flex-grow overflow-auto">
              {children}
            </div>
          </VerseBackground>
        <Footer />
      </body>
    </html>
  );
}
